import $config from "../nuxt.config";

export const decisionInPrincipleAPI = {
  getDataUrl: `${$config.b2cEnv}`,
  postDataURL: `${self.$config.dipPostUri}`,
  dbHeaders: {
    headers: {
      "Ocp-Apim-Subscription-Key": "c5511a6b5336408d8352aa7f9b327ef9",
    },
  },
  addressLookupHeaders: {
    headers: { "x-api-key": `${self.$config.addressApiToken}` },
  },
};

export const dataTemplate = {
  Id: "",
  IsDirty: true,
  Name: "",
  ApplicationDate: "",
  ApplyingForMortgage: "",
  TotalNetIncomeForMortgage: 0,
  IntendedBorrowing: "",
  TotalSavings: 0,
  PageOffSet: 1,
  SuitableFundsAvailable: true,
  RepayFromSaleOfProperty: false,
  RepayLoanWithSavings: false,
  Plot: {
    Id: "",
    IsDirty: false,
    Name: "",
    BuildCost: 0,
    TotalNetIncomeForMortgage: 0,
    TotalSavings: 0,
    DesignType: {
      Id: "",
      IsDirty: false,
      Name: "",
      MinCost: 0,
      MaxCost: 0,
    },
    Plot: {
      Id: "",
      IsDirty: false,
      Name: "",
      PlotId: "",
      TotalPlotLandCost: 0,
      Address: {
        Id: "",
        Address1: "",
        Address2: "",
        Address3: "",
        City: "",
        PostCode: "",
        County: "",
      },
    },
  },
  Applications: [
    {
      Id: "",
      IsDirty: false,
      Delete: false,
      CreatedOn: "",
      IsMainApplication: true,
      ApplicationNumber: 0,
      OnlyResidentialPropertyOwned: true,
      OnlyResidence: true,
      SavingsAmount: 0,
      UsingSavings: true, // is this field required? on the form we just capture the amount
      CreditCheckConsent: true,
      DataPrivacyConsent: true,
      ApplicantDateOfBirth: "",
      ApplicantEmail: "",
      ApplicantFirstName: "",
      ApplicantMiddleName: "",
      ApplicantLastName: "",
      ApplicantAddress: {
        Id: "",
        CreatedOn: "",
        Address1: "",
        Address2: "",
        Address3: "",
        City: "",
        County: "",
        PostCode: "",
      },
      ApplicationAddresses: [
        {
          Id: "",
          IsDirty: true,
          Delete: false,
          AddressType: "",
          ApplicationAddressNo: 0,
          OwnershipType: 1,
          EquityToContribute: 0,
          OutstandingMortgageAmount: 0,
          AmountUsedToRepayLoan: 0,
          EstimatedValue: 0,
          Address: {
            Id: "",
            IsDirty: false,
            Address1: "",
            Address2: "",
            Address3: "",
            City: "",
            PostCode: "",
            County: "",
          },
        },
      ],
    },
  ],
};

export const applicationTemplate = {
  Id: "",
  IsDirty: true,
  Delete: false,
  Unsaved: true,
  // CreatedOn: '',
  ApplicationNumber: 0,
  IsMainApplication: false,
  OnlyResidentialPropertyOwned: true,
  OnlyResidence: true,
  SavingsAmount: 0,
  RepayLoanWithSavings: true,
  CreditCheckConsent: true,
  DataPrivacyConsent: true,
  ApplicantDateOfBirth: "1960-01-01T00:00:00",
  ApplicantEmail: "",
  ApplicantFirstName: "",
  ApplicantMiddleName: "",
  ApplicantLastName: "",
  ApplicantAddress: {
    Id: "",
    // CreatedOn: '',
    Address1: "",
    Address2: "",
    Address3: "",
    City: "",
    County: "",
    PostCode: "",
  },
  ApplicationAddresses: [
    {
      Id: "",
      IsDirty: true,
      Delete: false,
      AddressType: "Home",
      ApplicationAddressNo: 0,
      OwnershipType: 1,
      EquityToContribute: 0,
      OutstandingMortgageAmount: 0,
      AmountUsedToRepayLoan: 0,
      EstimatedValue: 0,
      Address: {
        Id: "",
        IsDirty: true,
        Address1: "",
        Address2: "",
        Address3: "",
        City: "",
        PostCode: "",
        County: "",
      },
    },
  ],
};

export const applicationAddressTemplate = {
  Id: "",
  IsDirty: true,
  Delete: false,
  Unsaved: true,
  AddressType: "Additional",
  ApplicationAddressNo: 0,
  OwnershipType: "SoleOwnership",
  EquityToContribute: 0,
  OutstandingMortgageAmount: 0,
  AmountUsedToRepayLoan: 0,
  EstimatedValue: 0,
  Address: {
    Id: "",
    IsDirty: true,
    Address1: "",
    Address2: "",
    Address3: "",
    City: "",
    PostCode: "",
    County: "",
  },
};

export const AddressTemplate = {
  Id: "",
  IsDirty: true,
  Address1: "",
  Address2: "",
  Address3: "",
  City: "",
  PostCode: "",
  County: "",
};
