const DOCUMENT_COLUMNS = [
  'NODE_ID',
  'SUITE',
  'TITLE',
  'DOCUMENT_REFERENCE',
  'DISCIPLINE',
  'LIFECYCLE_STAGE',
  'REVISION',
  'VOLUME',
  'DATE_OF_ISSUE',
  'DATE_OF_WITHDRAWAL',
  'HAS_PUBLIC_DOCUMENT',
].join(',')

export default DOCUMENT_COLUMNS
