pipelines:
  default:
    - step:
        name: Build and test
        image: node:14.18.1
        script:
          - rm -rf node_modules/ yarn.lock
          - yarn install --force
          - yarn build
          - yarn test
          - yarn chromatic --exit-once-uploaded
